name: Warlords
version: Echoes of Demise
authors: [ebic, Plikie]
main: com.ebicep.warlords.Warlords
depend: [ MultiWorld, HolographicDisplays, ProtocolLib ]
load: POSTWORLD
commands:
  me:
    description: Not happening.
    usage: Not happening.
  oldtest:
    description: Old test command
    usage: /oldtest

permissions:
  group.default:
    default: false
  group.gametester:
    default: false
  group.gamestarter:
    default: false
  group.contentcreator:
    default: false
  group.coordinator:
    default: false
  group.administrator:
    default: false
  group.patreon:
    default: false

  warlords.game.impostertoggle:
    description: Allows the user to start games with the imposter game mode
  warlords.game.megagame:
    description: Allows the user to start games with the mega game mode
  warlords.game.cooldowngame:
    description: Allows the user to start games with the cooldown reduced game mode