name: Warlords
version: New Leaf
author: ebic
main: com.ebicep.warlords.Warlords
depend: [ MultiWorld, HolographicDisplays, ProtocolLib ]
load: POSTWORLD
commands:
  start:
    description: Starts a new game.
    usage: /start [MAP | RANDOM]
  endgame:
    description: Force stops the game.
    usage: /endgame
  menu:
    description: Opens the game menu.
    usage: /menu
  shout:
    description: Shouts in game
    usage: /shout [MESSAGE]
  hotkeymode:
    description: Switches between hotkeymode and classic
    usage: /hotkeymode
  wl:
    description: Debug tools.
    usage: /wl [args] [bonus args]
  class:
    description: Select your class.
    usage: /class [class]
  getplayers:
    description: Gets Players in lobby
    usage: /getplayers
  test:
    description: Test Command
    usage: /test
  pq:
    description: Sets particle quality
    usage: /pq [LOW,MEDIUM,HIGH]
  spawntestdummy:
    description: Spawns Test Dummy
    usage: /spawntestdummy [TEAM] [TAKE DAMAGE (TRUE/FALSE) ]
  party:
    description: Party options
    aliases: [ party, p,
               partyclose, partyopen, pclose, popen,
               partyoutside, poutside
    ]
  stream:
    description: Creates a new party where anyone can join
    usage: /stream
  recordaveragedamage:
    description: Prints average damage taken
    usage: /recordaveragedamage
  chatchannelcommand:
    description: Changes chat channel or sends a mesasage in a different channel
    aliases: [ chat, achat, ac, pchat, pc ]
  me:
    description: Not happening.
    usage: /me
  bot:
    description: Runs bot commands
    usage: /bot
  lb:
    description: Leaderboard Commands
    usage: /lb
  recordgames:
    description: Toggles recording games
    aliases: [ recordgames, countgames ]
  games:
    description: Games stuff
    aliases: [ games ]