name: Warlords
version: Illusion Vanguard
authors: [ebic, Plikie]
main: com.ebicep.warlords.Warlords
depend: [ MultiWorld, HolographicDisplays, ProtocolLib ]
load: POSTWORLD
commands:
  me:
    description: Not happening.
    usage: Not happening.
  setwave:
    description: Set the wave counter in Wave Defense
    usage: /setwave
  currency:
    description: Edit the currency in Wave Defense
    usage: /currency
  guild:
    description: Guild
    aliases: [ guild, g ]

permissions:
  group.default:
    default: false
  group.gametester:
    default: false
  group.gamestarter:
    default: false
  group.contentcreator:
    default: false
  group.coordinator:
    default: false
  group.administrator:
    default: false
  warlords.game.impostertoggle:
    description: Allows the user to start games with the imposter game mode
  warlords.game.megagame:
    description: Allows the user to start games with the mega game mode
  warlords.game.cooldowngame:
    description: Allows the user to start games with the cooldown reduced game mode