name: Warlords
version: Illusion Vanguard
authors: [ebic, Plikie]
main: com.ebicep.warlords.Warlords
depend: [ MultiWorld, HolographicDisplays, ProtocolLib ]
load: POSTWORLD
commands:
  party:
    description: Party options
    aliases: [ party, p ]
  stream:
    description: Creates a new party where anyone can join
    usage: /stream
  me:
    description: Not happening.
    usage: Not happening.
  bot:
    description: Runs bot commands
    usage: /bot
  queue:
    description: Queue system
    aliases: [ queue ]
  discord:
    description: Link and unlink discord account with minecraft account
    aliases: [ discord ]
  poll:
    description: Poll stuff
    aliases: [ poll ]
  setwave:
    description: Set the wave counter in Wave Defense
    usage: /setwave
  currency:
    description: Edit the currency in Wave Defense
    usage: /currency
  guild:
    description: Guild
    aliases: [ guild, g ]

permissions:
  group.default:
    default: false
  group.gametester:
    default: false
  group.gamestarter:
    default: false
  group.contentcreator:
    default: false
  group.coordinator:
    default: false
  group.administrator:
    default: false
  warlords.game.impostertoggle:
    description: Allows the user to start games with the imposter game mode
  warlords.game.megagame:
    description: Allows the user to start games with the mega game mode
  warlords.game.cooldowngame:
    description: Allows the user to start games with the cooldown reduced game mode