name: Warlords
version: 1.0.0
author: ebic
main: com.ebicep.warlords.Warlords
depend: [ MultiWorld ]
commands:
  start:
    description: Starts a new game.
    usage: /start [MAP | RANDOM]
  endgame:
    description: Force stops the game.
    usage: /endgame
  menu:
    description: Opens the game menu.
    usage: /menu
  shout:
    description: Shouts in game
    usage: /shout [MESSAGE]
  hotkeymode:
    description: Switches between hotkeymode and classic
    usage: /hotkeymode
  wldebug:
    description: Debug tools.
    usage: /wldebug [args]
