name: Warlords
version: 0.0.3
author: ebic
main: com.ebicep.warlords.Warlords
depend: [ MultiWorld ]
commands:
  start:
    description: Starts a new game.
    usage: /start [MAP | RANDOM]
  endgame:
    description: Force stops the game.
    usage: /endgame
  class:
    description: Select your class.
    usage: /class [CLASS]
  menu:
    description: Opens the game menu. Later to be removed.
    usage: /menu
  shout:
    description: Shouts in game
    usage: /shout [MESSAGE]
  hotkeymode:
    description: Switches between hotkeymode and classic
    usage: /hotkeymode
  hitbox:
    description: changes hitbox of fallen soul
    usage: /hitbox
  speed:
    description: changes speed of fallen soul
    usage: /speed
  wldebug:
    description: Debug tools.
    usage: /wldebug [args]
