name: Warlords
version: 1.0
author: ebic
main: com.ebicep.warlords.Warlords
depend: [MultiWorld]
commands:
  start:
    description: Starts a new game.
    usage: /start [MAP | RANDOM]
  endgame:
    description: Force stops the game.
    usage: /endgame
  class:
    description: Select your class.
    usage: /class [CLASS]
  menu:
    description: Opens the game menu. Later to be removed.
    usage: /menu
  shout:
    description: Shouts in game
    usage: /shout [MESSAGE]

